"""empty message

Revision ID: b6810ed567c8
Revises: 0fe688ef353b
Create Date: 2021-06-16 21:10:16.200166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6810ed567c8'
down_revision = '0fe688ef353b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_salary', sa.Column('data_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_salary', 'data_id')
    # ### end Alembic commands ###
