"""empty message

Revision ID: db651a2694ab
Revises: b6810ed567c8
Create Date: 2021-06-16 21:13:01.182156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db651a2694ab'
down_revision = 'b6810ed567c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_stats', sa.Column('data_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_stats', 'data_id')
    # ### end Alembic commands ###
